apiVersion: skaffold/v1beta10
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: gcr.io/dht-temperature-238413/dht-backend
    context: backend
  # - image: gcr.io/own-gcr/dht-pi
  #   context: pi
# defines the Kubernetes manifests to deploy on each run
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
# - name: cloudbuild
#   build:
#     googleCloudBuild: {}
- name: local
  activation:
  - command: dev
  build:
    artifacts:
    - image: gcr.io/dht-temperature-238413/dht-backend
      context: backend
    # - image: gcr.io/own-gcr/dht-pi
    #   context: pi
    local: {}
    # gcloud beta run deploy dht-backend   --image gcr.io/dht-temperature-238413/dht-backend