apiVersion: v1
kind: Service
metadata:
  name: dht-backend
  labels:
    app: dht
    tier: backend
spec:
  type: ClusterIP
  selector:
    app: dht-backend
    tier: backend
  ports:
  - port: 8080
    targetPort: http-server
