apiVersion: apps/v1
kind: Deployment
metadata:
  name: dht-pi
  labels:
    app: dht-pi
    tier: data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dht-pi
      tier: data
  template:
    metadata:
      labels:
        app: dht-pi
        tier: data
    spec:
      containers:
      - name: dht-pi
        image: gcr.io/dht-temperature-238413/dht-pi
        ports:
        - name: http-server
          containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: GUESTBOOK_API_ADDR
          value: node-guestbook-backend:8080
