apiVersion: v1
kind: Service
metadata:
  name: dht-pi
  labels:
    app: dht-pi
    tier: data
spec:
  type: LoadBalancer
  selector:
    app: dht-pi
    tier: data
  ports:
  - port: 80
    targetPort: http-server